util/cperf.py: run_experiment(): Fix, turn clients argument into list
For example, `cp_basic` calls this function with "range" objects, instead of
`lists` objects. This causes, Python 3.8.0 (Ubuntu 18.04), 3.10.6
(Ubuntu 22.04) and 3.11.2 (Debian 12) to complain:

Traceback (most recent call last):
  File "<PATH>/HomaModule/./util/cp_basic", line 75, in <module>
    run_experiment("homa_latency", range(0, 1), o)
  File "<PATH>/HomaModule/./util/cperf.py", line 651, in run_experiment
    exp_nodes = list(set(options.servers + clients))
TypeError: can only concatenate list (not "range") to list

Signed-off-by: Joachim Foerster <joachim.foerster@missinglinkelectronics.com>